In [1]:
#example 1: numpy.concatenate()
import numpy as np  
x=np.array([[1,2],[3,4]])  
y=np.array([[12,30]])  
z=np.concatenate((x,y))  
z  

array([[ 1,  2],
       [ 3,  4],
       [12, 30]])

In [2]:
#example 2: numpy.concatenate() with axis=0
import numpy as np  
x=np.array([[1,2],[3,4]])  
y=np.array([[12,30]])  
z=np.concatenate((x,y), axis=0)  
z 

array([[ 1,  2],
       [ 3,  4],
       [12, 30]])

In [3]:
#example 3: numpy.concatenate() with axis=1
import numpy as np  
x=np.array([[1,2],[3,4]])  
y=np.array([[12,30]])  
z=np.concatenate((x,y.T), axis=1)  
z  

array([[ 1,  2, 12],
       [ 3,  4, 30]])

In [4]:
#example 4: numpy.concatenate() with axis=None
import numpy as np  
x=np.array([[1,2],[3,4]])  
y=np.array([[12,30]])  
z=np.concatenate((x,y), axis=None)  
z  

array([ 1,  2,  3,  4, 12, 30])

In [5]:
#example 5: np.ma.concatenate()
import numpy as np  
x=np.ma.arange(3)  
y=np.arange(3,6)  
x[1]=np.ma.masked  
x  
y  
z1=np.concatenate([x,y])  
z2=np.ma.concatenate([x,y])  
z1  
z2  

masked_array(data=[0, --, 2, 3, 4, 5],
             mask=[False,  True, False, False, False, False],
       fill_value=999999)