In [1]:
#example 1:
import numpy as np  
from io import StringIO   # StringIO behaves like a file object
c = StringIO("0 1\n2 3")
np.loadtxt(c)

array([[0., 1.],
       [2., 3.]])

In [2]:
#example 2:
import numpy as np  
d = StringIO("M 21 72\nF 35 58")
np.loadtxt(d, dtype={'names': ('gender', 'age', 'weight'),
                     'formats': ('S1', 'i4', 'f4')})

array([(b'M', 21, 72.), (b'F', 35, 58.)],
      dtype=[('gender', 'S1'), ('age', '<i4'), ('weight', '<f4')])

In [4]:
#example 3:
import numpy as np  
from io import StringIO  
c = StringIO("1,0,2\n3,0,4")
x, y = np.loadtxt(c, delimiter=',', usecols=(0, 2), unpack=True)
x, y

(array([1., 3.]), array([2., 4.]))

In [5]:
#example shows how converters can be used to convert a field with a trailing minus sign into a negative number.
s = StringIO('10.01 31.25-\n19.22 64.31\n17.57- 63.94')
def conv(fld):
    return -float(fld[:-1]) if fld.endswith(b'-') else float(fld)

np.loadtxt(s, converters={0: conv, 1: conv})

array([[ 10.01, -31.25],
       [ 19.22,  64.31],
       [-17.57,  63.94]])