In [3]:
#example 1: np.argsort()
import numpy as np  
a=np.array([456,11,63])  
a  
b=np.argsort(a)  
a, b  

(array([456,  11,  63]), array([1, 2, 0], dtype=int64))

In [4]:
#example 2: For 2-D array( sorts along first axis (down))
import numpy as np  
a = np.array([[0, 5], [3, 2]])  
indices = np.argsort(a, axis=0)    
indices  

array([[0, 1],
       [1, 0]], dtype=int64)

In [12]:
#example 3: For 2-D array(alternative of axis=0)
import numpy as np  
a = np.array([[0, 5], [3, 2]])  
indices = np.argsort(a, axis=0)  
indices,  np.take_along_axis(a, indices, axis=0)  

(array([[0, 1],
        [1, 0]], dtype=int64),
 array([[0, 2],
        [3, 5]]))

In [6]:
#example 4: For 2-D array( sorts along last axis (across))
import numpy as np  
a = np.array([[0, 5], [3, 2]])  
indices = np.argsort(a, axis=1)    
indices  

array([[0, 1],
       [1, 0]], dtype=int64)

In [10]:
#example 5: For 2-D array(alternative of axis=1)
import numpy as np  
a = np.array([[0, 5], [3, 2]])  
indices = np.argsort(a, axis=1)  
indices, np.take_along_axis(a, indices, axis=1) 

(array([[0, 1],
        [1, 0]], dtype=int64),
 array([[0, 5],
        [2, 3]]))

In [9]:
#example 6: For N-D array
import numpy as np  
a = np.array([[0, 5], [3, 2]])  
indices = np.unravel_index(np.argsort(a, axis=None), a.shape)  
indices, a[indices]  # same as np.sort(a, axis=None)  

((array([0, 1, 1, 0], dtype=int64), array([0, 1, 0, 1], dtype=int64)),
 array([0, 2, 3, 5]))

In [14]:
#example 7: Sorting with keys
import numpy as np  
a= np.array([(0, 5), (3, 2)], dtype=[('x', '<i4'), ('y', '<i4')])  
b=np.argsort(a, order=('x','y'))  
c=np.argsort(a, order=('y','x'))  
a, b, c  

(array([(0, 5), (3, 2)], dtype=[('x', '<i4'), ('y', '<i4')]),
 array([0, 1], dtype=int64),
 array([1, 0], dtype=int64))