In [1]:
#example 1:
import numpy as np  
a=np.unique([1,2,3,4,3,6,2,4])  
a  

array([1, 2, 3, 4, 6])

In [2]:
#example 2:
a=np.array([[1,2,2,3,9],[1,4,3,5,8]])  
b=np.unique(a)  
a, b  

(array([[1, 2, 2, 3, 9],
        [1, 4, 3, 5, 8]]),
 array([1, 2, 3, 4, 5, 8, 9]))

In [3]:
#example 3:
import numpy as np  
a = np.array([[1, 1, 0], [1, 1, 0], [2, 3, 4],[5, 9, 8],[2, 3, 4]])  
b=np.unique(a, axis=0)  
a, b  

(array([[1, 1, 0],
        [1, 1, 0],
        [2, 3, 4],
        [5, 9, 8],
        [2, 3, 4]]),
 array([[1, 1, 0],
        [2, 3, 4],
        [5, 9, 8]]))

In [5]:
#example 4:
import numpy as np  
a = np.array([[1, 1, 0], [1, 1, 0], [2, 2, 4],[5, 5, 8],[2, 2, 4]])  
b=np.unique(a, axis=1)  
a, b  
# Note: When we set axis as 1 then this function returns the unique columns from the source array.

(array([[1, 1, 0],
        [1, 1, 0],
        [2, 2, 4],
        [5, 5, 8],
        [2, 2, 4]]),
 array([[0, 1],
        [0, 1],
        [4, 2],
        [8, 5],
        [4, 2]]))

In [8]:
#example 5: Use return_index
import numpy as np  
a = np.array(['d', 'b', 'b', 'z', 'a'])  
result, indices=np.unique(a,return_index=True)  
result, indices, a[indices] 

(array(['a', 'b', 'd', 'z'], dtype='<U1'),
 array([4, 1, 0, 3], dtype=int64),
 array(['a', 'b', 'd', 'z'], dtype='<U1'))

In [9]:
#example 6: Use return_inverse We can reconstruct the input array from the unique values in the following way:
import numpy as np  
a = np.array([1, 2, 6, 4, 5, 3, 2])  
result, indices=np.unique(a,return_inverse=True)  
result, indices, a[indices]  

(array([1, 2, 3, 4, 5, 6]),
 array([0, 1, 5, 3, 4, 2, 1], dtype=int64),
 array([1, 2, 3, 4, 5, 6, 2]))