In [6]:
#example 1: numpy.array()
import numpy as np  
arr=np.array([1,2,3])  
arr  

array([1, 2, 3])

In [7]:
#example 2:
import numpy as np  
arr=np.array([1,2.,3.])  
arr  

array([1., 2., 3.])

In [8]:
#example 3: More than one dimensions
import numpy as np  
arr=np.array([[1,2.,3.],[4.,5.,7]])  
arr  

array([[1., 2., 3.],
       [4., 5., 7.]])

In [9]:
#example 4: Minimum dimensions: 2
import numpy as np  
arr=np.array([1,2.,3.],ndmin=2)  
arr  

array([[1., 2., 3.]])

In [10]:
#example 5: Type provided
import numpy as np  
arr=np.array([12,45.,3.],dtype=complex)  
arr  

array([12.+0.j, 45.+0.j,  3.+0.j])

In [11]:
#example 6: Creating an array from sub-classes
import numpy as np  
arr=np.array(np.mat('1 2;3 4'))  
arr  
arr=np.array(np.mat('1 2;3 4'),subok=True)  
arr 

matrix([[1, 2],
        [3, 4]])