In [1]:
#example 1: np.where()
#This function returns the array with elements from x where the condition is True and elements from y elsewhere.
import numpy as np  
a=np.arange(12)  
b=np.where(a<6,a,5*a)  
b  

array([ 0,  1,  2,  3,  4,  5, 30, 35, 40, 45, 50, 55])

In [2]:
#example 2: For multidimensional array
import numpy as np  
a=np.arange(12)  
b=np.where([[True, False], [True, True]],[[1, 2], [3, 4]],[[9, 8], [7, 6]])  
b  

array([[1, 8],
       [3, 4]])

In [3]:
#example 3: Broadcasting x, y, and condition
import numpy as np  
x, y = np.ogrid[:3, :4]  
a=np.where(x > y, x, 10 + y)  
a  

array([[10, 11, 12, 13],
       [ 1, 11, 12, 13],
       [ 2,  2, 12, 13]])

In [4]:
#example 4: Broadcasting specific value
import numpy as np
x=np.array([[0,1,2],[0,2,5],[0,4,8]])  
y=np.where(x<4,x,-2)  
y  

array([[ 0,  1,  2],
       [ 0,  2, -2],
       [ 0, -2, -2]])