In [1]:
#example 1: numpy.transpose()
import numpy as np  
a= np.arange(6).reshape((2,3))  
a  
b=np.transpose(a)  
a, b  

(array([[0, 1, 2],
        [3, 4, 5]]),
 array([[0, 3],
        [1, 4],
        [2, 5]]))

In [2]:
#example 2: numpy.transpose() with axis
import numpy as np  
a= np.array([[1, 2], [4, 5], [7, 8]])  
a  
b=np.transpose(a, (1,0))  
a, b   

(array([[1, 2],
        [4, 5],
        [7, 8]]),
 array([[1, 4, 7],
        [2, 5, 8]]))

In [7]:
#example 3: Reposition elements using numpy.transpose()
import numpy as np  
a=np.ones((12,32,123,64))  
b=np.transpose(a,(1,3,0,2)).shape  
c=np.transpose(a,(0,3,1,2)).shape  
b, c  

((32, 64, 12, 123), (12, 64, 32, 123))