In [1]:
#example 1: numpy.zeros() without dtype and order
#This function returns a ndarray. The output array is the array with specified shape, dtype, order, and contains zeros.
import numpy as np  
a=np.zeros(6)  
a  

array([0., 0., 0., 0., 0., 0.])

In [2]:
#example 2: numpy.zeros() without order
import numpy as np  
a=np.zeros((6,), dtype=int)  
a   

array([0, 0, 0, 0, 0, 0])

In [4]:
#example 3: numpy.zeros() with shape
import numpy as np  
a=np.zeros((5,4))  
a  

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
#example 4: numpy.zeros() with the shape
import numpy as np  
s1=(3,2)  
a=np.zeros(s1)  
a  

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [7]:
#example 5: numpy.zeros() with custom dtype
import numpy as np  
a=np.zeros((3,), dtype=[('x', 'i4'), ('y', 'i4')])  
a  

array([(0, 0), (0, 0), (0, 0)], dtype=[('x', '<i4'), ('y', '<i4')])