In [1]:
#example 1:
import numpy as np  
x= np.arange(12)  
y=np.clip(x, 3, 10)  
x, y  

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([ 3,  3,  3,  3,  4,  5,  6,  7,  8,  9, 10, 10]))

In [5]:
#example 2:
import numpy as np  
a = np.arange(12)  
np.clip(a, 3, 9, out=a), a  

(array([3, 3, 3, 3, 4, 5, 6, 7, 8, 9, 9, 9]),
 array([3, 3, 3, 3, 4, 5, 6, 7, 8, 9, 9, 9]))

In [6]:
#example 3:
import numpy as np  
a = np.arange(12)  
np.clip(a, [3, 4, 1, 1, 1, 4, 4, 4, 4, 4, 5, 6], 8)  

array([3, 4, 2, 3, 4, 5, 6, 7, 8, 8, 8, 8])