In [1]:
#example 1: C-like index ordering
import numpy as np  
x=np.arange(12)  
y=np.reshape(x, (4,3))  
x  
y  

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [2]:
#example 2: Equivalent to C ravel then C reshape
import numpy as np  
x=np.arange(12)  
y=np.reshape(np.ravel(x),(3,4))  
x  
y  

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
#example 3: Fortran-like index ordering
import numpy as np  
x=np.arange(12)  
y=np.reshape(x, (4, 3), order='F')  
x  
y  

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [6]:
#example 4: Fortran-like index ordering
import numpy as np  
x=np.arange(12)  
y=np.reshape(np.ravel(x, order='F'), (4, 3), order='F')  
x
y  

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [7]:
#example 5: The unspecified value is inferred to be 2
import numpy as np  
x=np.arange(12)  
y=np.reshape(x, (2, -1))  
x  
y  

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])